// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCap7oFJELquyQH8VWyA1jkUaBcXD0f2qQ',
    appId: '1:772630671009:web:f3488f7608c11bc2d60ae0',
    messagingSenderId: '772630671009',
    projectId: 'mydiary-904f9',
    authDomain: 'mydiary-904f9.firebaseapp.com',
    storageBucket: 'mydiary-904f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBW_jw3Z-grPoVSwNfUfX-xmj6XKhj_E',
    appId: '1:772630671009:android:81795dc17ecdc060d60ae0',
    messagingSenderId: '772630671009',
    projectId: 'mydiary-904f9',
    storageBucket: 'mydiary-904f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_07LxmNe14g4_uDXiIfrrc5-yFDJAUp8',
    appId: '1:772630671009:ios:896cbc6050369089d60ae0',
    messagingSenderId: '772630671009',
    projectId: 'mydiary-904f9',
    storageBucket: 'mydiary-904f9.appspot.com',
    iosClientId: '772630671009-5jb7ct0oc84u82k40qfeevvrbeba2d1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodaysdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_07LxmNe14g4_uDXiIfrrc5-yFDJAUp8',
    appId: '1:772630671009:ios:6443a12f3a7dafafd60ae0',
    messagingSenderId: '772630671009',
    projectId: 'mydiary-904f9',
    storageBucket: 'mydiary-904f9.appspot.com',
    iosClientId: '772630671009-sdnrm2o9nvo8rst1eba4lld6fv07miu4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mytodaysdiary.RunnerTests',
  );
}
