// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfwohr7AalrxcM5dIHrI8SGtv4ebpe25g',
    appId: '1:875587374214:web:7707cc5c29b2e125f91507',
    messagingSenderId: '875587374214',
    projectId: 'diarypro-de6f4',
    authDomain: 'diarypro-de6f4.firebaseapp.com',
    storageBucket: 'diarypro-de6f4.appspot.com',
    measurementId: 'G-D9GVVP9G86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnL91Ziz1K8SyLsnZ8t8l2Q1WeY9cqRew',
    appId: '1:875587374214:android:b5b7fa3c20bea1b4f91507',
    messagingSenderId: '875587374214',
    projectId: 'diarypro-de6f4',
    storageBucket: 'diarypro-de6f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOHlfvWxs6BqsWeJjYP6B13ReGhFsIJSs',
    appId: '1:875587374214:ios:b940136037d31b06f91507',
    messagingSenderId: '875587374214',
    projectId: 'diarypro-de6f4',
    storageBucket: 'diarypro-de6f4.appspot.com',
    iosBundleId: 'com.example.mytodaysdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOHlfvWxs6BqsWeJjYP6B13ReGhFsIJSs',
    appId: '1:875587374214:ios:2222cc20373b5852f91507',
    messagingSenderId: '875587374214',
    projectId: 'diarypro-de6f4',
    storageBucket: 'diarypro-de6f4.appspot.com',
    iosBundleId: 'com.example.mytodaysdiary.RunnerTests',
  );
}
